- platform: cisco_iosxe
  host: 192.168.10.41
  auth_username: admin
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  transport: paramiko
  timeout_socket: 5
  timeout_transport: 10

- platform: cisco_iosxe
  host: 192.168.10.42
  auth_username: admin
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  transport: paramiko
  timeout_socket: 5
  timeout_transport: 10

- platform: cisco_iosxe
  host: 192.168.10.43
  auth_username: admin
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  transport: paramiko
  timeout_socket: 5
  timeout_transport: 10
- platform: cisco_iosxe
  host: 192.168.10.44
  auth_username: admin
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  transport: paramiko
  timeout_socket: 5
  timeout_transport: 10
- platform: cisco_iosxe
  host: 192.168.10.45
  auth_username: admin
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  transport: paramiko
  timeout_socket: 5
  timeout_transport: 10
- platform: cisco_iosxe
  host: 192.168.10.46
  auth_username: admin
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  transport: paramiko
  timeout_socket: 5
  timeout_transport: 10
- platform: cisco_iosxe
  host: 192.168.10.47
  auth_username: admin
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  transport: paramiko
  timeout_socket: 5
  timeout_transport: 10
- platform: cisco_iosxe
  host: 192.168.10.48
  auth_username: admin
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  transport: paramiko
  timeout_socket: 5
  timeout_transport: 10
- platform: cisco_iosxe
  host: 192.168.10.49
  auth_username: admin
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  transport: paramiko
  timeout_socket: 5
  timeout_transport: 10